@Library('jenkins-shared-lib') _

pipeline {

    agent any
    

    environment {
        ENV = 'uat'
    }

    stages {

        stage('Load Config') {
            steps {
                 
                    ls -al && pwd && docker -v
                    
                }
            }
        }
}