@Library('jenkins-shared-lib') _

pipeline {

    agent any
    

    environment {
        ENV = 'uat'
    }

    stages {

        stage('Load Config') {
            steps {
                container('infra') {
                    script {
                        ls -al && pwd && docker -v
                        }
                    }
                }
            }
        }
}