@Library('jenkins-shared-lib') _

pipeline {

    agent any
    
    stages {
        stage('Build') {
            steps {
                echo 'Building..' 
            }
        }
        stage('docker') {
            steps {
                docker -v
            }
        }
    }
}